// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.guymoyo.ntc.domain;

import com.guymoyo.ntc.domain.Entreprise;
import com.guymoyo.ntc.domain.Projet;
import com.guymoyo.ntc.domain.TypeProjet;
import com.guymoyo.ntc.domain.UserAccount;
import com.guymoyo.ntc.domain.UserAccountDataOnDemand;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ProjetDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProjetDataOnDemand: @Component;
    
    private Random ProjetDataOnDemand.rnd = new SecureRandom();
    
    private List<Projet> ProjetDataOnDemand.data;
    
    @Autowired
    private UserAccountDataOnDemand ProjetDataOnDemand.userAccountDataOnDemand;
    
    public Projet ProjetDataOnDemand.getNewTransientProjet(int index) {
        Projet obj = new Projet();
        setCreatedAt(obj, index);
        setCreatedBy(obj, index);
        setDateDebut(obj, index);
        setDateFin(obj, index);
        setEntreprise(obj, index);
        setNom(obj, index);
        setTypeProjet(obj, index);
        return obj;
    }
    
    public void ProjetDataOnDemand.setCreatedAt(Projet obj, int index) {
        Date createdAt = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedAt(createdAt);
    }
    
    public void ProjetDataOnDemand.setCreatedBy(Projet obj, int index) {
        UserAccount createdBy = userAccountDataOnDemand.getRandomUserAccount();
        obj.setCreatedBy(createdBy);
    }
    
    public void ProjetDataOnDemand.setDateDebut(Projet obj, int index) {
        Date dateDebut = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateDebut(dateDebut);
    }
    
    public void ProjetDataOnDemand.setDateFin(Projet obj, int index) {
        Date dateFin = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateFin(dateFin);
    }
    
    public void ProjetDataOnDemand.setEntreprise(Projet obj, int index) {
        Entreprise entreprise = null;
        obj.setEntreprise(entreprise);
    }
    
    public void ProjetDataOnDemand.setNom(Projet obj, int index) {
        String nom = "nom_" + index;
        obj.setNom(nom);
    }
    
    public void ProjetDataOnDemand.setTypeProjet(Projet obj, int index) {
        TypeProjet typeProjet = TypeProjet.class.getEnumConstants()[0];
        obj.setTypeProjet(typeProjet);
    }
    
    public Projet ProjetDataOnDemand.getSpecificProjet(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Projet obj = data.get(index);
        return Projet.findProjet(obj.getId());
    }
    
    public Projet ProjetDataOnDemand.getRandomProjet() {
        init();
        Projet obj = data.get(rnd.nextInt(data.size()));
        return Projet.findProjet(obj.getId());
    }
    
    public boolean ProjetDataOnDemand.modifyProjet(Projet obj) {
        return false;
    }
    
    public void ProjetDataOnDemand.init() {
        data = Projet.findProjetEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Projet' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.guymoyo.ntc.domain.Projet>();
        for (int i = 0; i < 10; i++) {
            Projet obj = getNewTransientProjet(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
